### ISSUE TITLE
Sorguyu->Pdox Cevirme

### ISSUE THREAD

**Issue by emresaracoglu** [izniburak/pdox#10]
Merhaba

Asagidaki sorguyu, Pdox'e göre düzenlemeye çalıştım ancak başarılı olamadim, yardımcı olabilir misiniz?

```
$sql = "SELECT * FROM `tabloA` WHERE (`testA` != '' AND `testB` != '')";
$result = $conn->query($sql);
if ($result->num_rows > 0) {
  while($row = $result->fetch_assoc()) { 
   ...
```

**Comment by izniburak** [comment]
Basitçe şu şekilde yazılabilir. 

```php
$records= $db->table("tableA")->where("(testA != ? AND testB != ?)", ["", ""])->getAll();
if($db->numRows() > 0) {
    foreach($records as $record)
    {
        // some code...
    }
}
```

Dönen sonuçlar **(object)** olarak geleceği için, foreach içerisinde erişirken **$record->field** tarzında erişmeniz lazım. Eğer kayıtları **dizi (array)** olarak almak isterseniz **->getAll("array")** olarak sorguyu çalıştırın. 

Kolay gelsin.
