### ISSUE TITLE
How to make query with UNION [ALL]

### ISSUE THREAD

**Issue by simp-lee** [izniburak/PDOx#105]
Thanks for your good job.
But, I can't find the usage of UNION [ALL] in the document, as following:
```
SELECT column,... FROM table1 
UNION [ALL]
SELECT column,... FROM table2
...
```
Any solutions?
Or how to use native SQL statements in pdox?

**Comment by izniburak** [comment]
Hi @lee-php ,
Thanks for feedback. 
For now, there is no a method to use `union` command directly. But you can type native SQL code via `query` method.
You can check this: https://github.com/izniburak/PDOx/blob/master/DOCS.md#query

Thanks.

**Comment by simp-lee** [comment]
Thanks, izniburak. I will try native SQL until your improvement.
