### ISSUE TITLE
JSON_REPLACE 

### ISSUE THREAD

**Issue by SinanSS** [izniburak/PDOx#108]
update işlemi yaparken JSON_REPLACE fonksiyonunu nasıl kullanabilirim?

**Comment by izniburak** [comment]
Merhabalari

Şu an PDOx içerisinde SQL için JSON metotları desteklenmiyor. Bunları raw query yazarak kullanabilirsiniz. Dokümantasyona göz atarak raw query hakkında bilgi alabilirsiniz.

**Comment by SinanSS** [comment]
Çok teşekkür ederim hocam iyi çalışmalar dilerim :)
