### ISSUE TITLE
SQLite Ile Tablo Gosterimi ve Veri Ekleme

### ISSUE THREAD

**Issue by emresaracoglu** [izniburak/pdox#11]
Merhaba

Onceki yardimlariniz icin tesekkur ederim,
SQLite veritabani icerisine veri ekleme/guncelleme yapabilirken, veri ekleme kisminda hatami bulamiyorum. 

```
$browers = $db->table('albums')->getAll();
foreach($browers as $brower) {
    echo $brower->AlbumId;
} 
```

Ayrica SQLite veritanindaki tablolari ekrana PDOx ile nasil yazdirilabilir? Tablo yazdirmak icin SQL giris alani olmadigi icin nasil bir yol izlenmelidir?

Ornegin; 

`Album, Artist, Customer, Employee, Genre, Invoice, InvoiceLine, MediaType, Playlist, PlaylistTrack, Track.`

Tablo isimlerini yazdirmak eger mumkun ise tabloya ait verilerin _(tablo boyutu, satir sayisi vs)_ ekrana yazilmasi mumkun mu?

Yardimlariniz ve vakit ayirdiginiz icin en icten dileklerimle tesekkur ederim.

**Comment by izniburak** [comment]
Gönderdiğiniz kodda herhangi bir veri ekleme işlemi bulunmuyor. Tam olarak nerede hata alıyorsunuz? 
PDOx size ham SQL kodları ile işlemler yapmanızı sağlar. Veritabanındaki tabloları adlarını, boyutu vs gibi bilgileri yazdırmak için bunlara uygun SQL komutlarını kullanmanız gerek. Bu komutları PDOx sınıfının query() metodu ile kullanabilirsiniz.
