### ISSUE TITLE
SQLite Ile Veri Cekimi

### ISSUE THREAD

**Issue by emresaracoglu** [izniburak/pdox#12]
Merhaba,

```
<?php 
require 'vendor/autoload.php';
$config = [
    'host'      => 'localhost',
    'driver'    => 'sqlite',
    'database'  => 'test.sqlite',
    'username'  => '',
    'password'  => '',
    'charset'   => 'utf8',
    'collation' => 'utf8_general_ci',
    'prefix'     => ''
];
$db = new \Buki\Pdox($config);
$records = $db->table('sqliteTest')->getAll();
foreach($records as $record)
{
	echo $record->Area. '<br />' ;
}
```

Bununla `test.sqlite` adindaki veritabani dosyasi icerindeki verileri ekrana yazdiramiyorum.
Veritabani dosyasi yada tablo adininda degisiklik yapildigi takdirde `Database Error` ile karsilasirken dogru bilgilerle beyaz ekran aliyorum.

SQLite ile veri cekiminde nerede hata yapiyorum?

Tekrardan tesekkurler,
mutlu gunler

**Comment by izniburak** [comment]
Veritabanı dosyanız hangi dizinde bulunuyor? Gerekli tabloları ve alanları oluşturdunuz mu?

**Comment by emresaracoglu** [comment]
Sinif ve SQLite veritabani dosyasi ayni dizinde yer aliyor. Harici bir PDO kodu ile ilgili veritabanina baglantiyi saglayabiliyorum. Gun icerinde birkac saatimi verdim ancak sonuca maalesef ulasamadim. 

Bahsettigim harici kod: 
```
$Sonuclar = $db->query('SELECT * FROM sqliteTest'); 
$Row = $Sonuclar->fetchArray();
echo $Row['Area'];
```

**Comment by izniburak** [comment]
Yüksek ihtimalle veritabanı dosyasını okuyamıyor. Dizinde ve erişimde problem oluyor sanıyorum ki. Aldığınız veritabanı hatası nedir?

**Comment by emresaracoglu** [comment]
Eger `config` icerisinde yanlis veri degisikligi yaparsam dogal olarak `Database Error` basligi altinda hata aliyorum ancak tum path ve girilen bilgiler dogru oldugu halde herhangi hata belirtmeden beyaz sayfa ile karsilasiyorum. Eger veritabani dosyasini incelemek isterseniz dusuncesiyle dosyayi ekledim.
[sqliteTest.zip](https://github.com/izniburak/pdox/files/496758/sqliteTest.zip)

**Comment by emresaracoglu** [comment]
Bir gelisme var mi acaba?

**Comment by izniburak** [comment]
Kendimde bulunan bir SQLite örneği için deneme yaptım ama herhangi bir sorun yaşamadım. Sizin göndermiş olduğunuz veritabanı için henüz test etme imkanım olmadı en kısa sürede ona da bakacağım.

**Comment by izniburak** [comment]
Merhabalar, SQLite dosyanızı hangi dizinde bulunduruyorsunuz?

**Comment by emresaracoglu** [comment]
Merhaba, PDOx Sinifinin bulundugu klasor icerisinde yer aliyor.

**Comment by emresaracoglu** [comment]
Yeniden merhaba, 
Acaba sorum hakkinda bir gelisme var mi? 
Eger vaktiniz yok ise konuyu kapatabilirsiniz.

**Comment by izniburak** [comment]
Merhabalar,

config ayarlarınızı nasıl yaptığınızı bilmediğim için herhangi bir şey diyemiyorum. Göndermiş olduğunuz sqlite dosyası ile tekrar kontrol yaptım ama, bilgileri doğru girdiğimde herhangi bir şekilde hata almadım. SQLite dosyanızın tam yerini, tablolarınızı ve sorgularınızı tekrar kontrol etmenizi öneririm.

**Comment by emresaracoglu** [comment]
Dilerseniz test ettiginiz klasoru ZIP halinde ekte sunmaniz mumkun mu? Boylelikle hatayi karsilastirabilirim.

**Comment by izniburak** [comment]
Test ettikten sonra klasörü sildim ama, basitçe şu çekilde dizin durumları:

-vendor
-index.php
-db.sqlite

index.php içeriği:

```php
$config = [
    'host'      => 'localhost',
    'driver'    => 'sqlite',
    'database'  => 'db.sqlite',
    'username'  => '',
    'password'  => '',
    'charset'   => 'utf8',
    'collation' => 'utf8_general_ci',
    'prefix'     => ''
];

$db = new Buki\Pdox($config);

var_dump( $db->query("SELECT * FROM test_table") );
```

Ben bu şekilde herhangi bir beyaz sayfa hatası almadım. Aksine, yazdığım sorguya göre tablo yok, sorgu hatalı tarzında DB error hataları aldım.

**Comment by emresaracoglu** [comment]
Anliyorum tekrar deneyecegim, vaktiniz icin tesekkur ederim.
