### ISSUE TITLE
show/hide error

### ISSUE THREAD

**Issue by alieslamifard** [izniburak/pdox#14]
hi.
can i set error as false in config to do not call error() in production ?
:)

**Comment by izniburak** [comment]
Hi @alieslamifard ,
It's not possible at the moment, but it could. I'll add it to the development notes :)

**Comment by izniburak** [comment]
Hi! This feature added.

```php
require 'vendor/autoload.php';

$config = [
	'host'		=> 'localhost',
	'driver'	=> 'mysql',
	'database'	=> 'test',
	// other values ...
	'prefix'	 => '',
        'debug'     => false
];

$db = new \Buki\Pdox($config);
```

If the debug value is **true**, error messages are displayed. 
But, if it is **false**, the query returns false.
