### ISSUE TITLE
How cache works ?

### ISSUE THREAD

**Issue by jagroop** [izniburak/pdox#15]
Hi 
First of all thank you so much for making this AWESOME query builder :)
I was going through code, and i found some code related to cache
can you please tell me how exactly CACHE works in this query builder

Thanks.

**Comment by izniburak** [comment]
Hi @jagroop , 
First, I'm glad you liked the book and used it. :)
You can use the cache() method to cache queries that you write. ([PDOx Cache Method](https://github.com/izniburak/PDOx/blob/master/DOCS.md#cache))

If you do, you can set which directory holds the cache files.
For example:

```php
$config = [
    'host'      => 'localhost',
    'driver'    => 'mysql',
    'database'  => 'test',
    'username'  => 'root',
    'password'  => '',
    'charset'   => 'utf8',
    'collation' => 'utf8_general_ci',
    'prefix'     => '',
    'cachedir' => __DIR__ . '/cache/',
];

$db = new \Buki\Pdox($config);

$records = $db->table('users')
        ->select('id, name, surname, age')
        ->where('age', '>', 18)
        ->orderBy('id', 'desc')
        ->limit(20)
        ->cache(60) // 60 seconds
        ->getAll();

var_dump($records);
```

You can use the [documentation page](https://github.com/izniburak/PDOx/blob/master/DOCS.md) for detailed usage information of the PDOx library.

**Comment by jagroop** [comment]
thanks :)

**Comment by hakanbulgurlu** [comment]
Merhabalar;
Eline sağlık çok güzel geliştirilmiş. Bir çok projemde kullanıyorum. Bazı modüllerini geliştirmek zorunda kaldım. Birde cache clear koymak gerekiyor. Ancak ben Codeigniter içerisine entegre ettim cache clear kullandığımda sapıtıyor.

**Comment by izniburak** [comment]
Merhabalar @hakanbulgurlu ,
Öncelikle yorumlarınız için teşekkürler, bunları duymak çok sevindirici. PDOx içerisine otomatik olarak cache dosyalarını silen bir mekanizma entegre etmedim. Ben kendi projelerimde PDOx u kullandığımda, ortalama olarak kullanmış olduğum bir cache süresini belirleyip, (örneğin 15 dk) sonrasıda ayrı bir script yazıyorum ve cron'a ekliyorum; 15dk da bir çalışacak ve cache dosyasının time değerlerine göre oluşturulmasının üzerinden en az 15dk geçmiş olacak şekilde. Böylece background bir task olarak otomatik clear ediyorum. İşimi görüyor ama, ne kadar doğru bir yöntem; tartışılabilir.
