### ISSUE TITLE
Transactions support

### ISSUE THREAD

**Issue by tigusigalpa** [izniburak/pdox#17]
Hi!
Your library is great but is it possible to add transactions support?

**Comment by izniburak** [comment]
Hi @tigusigalpa ,
Unfortunately, there is no such support at the moment. I can work on this in the next updates. I also add this to my development notes. Thank you for your feedback :)

**Comment by izniburak** [comment]
Hi. It's a bit late but, I just added transaction support in PDOx. I'll update documantation soon. 
Simply for now;

```php
$db->transaction();
/**
 * your codes
 */
$db->commit(); /* OR */ $db->rollBack();
```
Thanks.
