### ISSUE TITLE
Var Olan Verinin Üstüne Ekleme

### ISSUE THREAD

**Issue by emresaracoglu** [izniburak/pdox#18]
Merhaba,

Tabloid yer alan miktarin üzerine belirlenmiş bir miktarin daha eklenmesini istiyorum. Klasik sorguda yapilan bu tarz işlemi, PDOx ile nasil yapilabilir?

Denediğim sorgu:
```
$data = [
    'kullanilanAlan' => 'kullanilanAlan' + 100000
]; $db->table('users')->where('user_id', 2)->update($data);
```

Teşekkürler!

**Comment by izniburak** [comment]
```php 
$db->query("UPDATE users SET kullanilanAlan = kullanilanAlan + 100000 WHERE user_id = ?", [2]);
```
şeklinde dener misiniz?

**Comment by emresaracoglu** [comment]
Teşekkür ederim
