### ISSUE TITLE
Join Issue

### ISSUE THREAD

**Issue by yvzshn** [izniburak/PDOx#2]
Merhaba, 
Dökümantasyonda eksik kalan join kısmını tamamlamanızı rica ediyorum.

**Comment by izniburak** [comment]
Kısa bir süre içerisinde join() ile alakalı ekleme yapacağım. Bir kaç düzenleme ve ekleme üzerinde çalışıyorum. Bugün - yarın eklemiş olurum. Takipte kalın. Saygılar.
