### ISSUE TITLE
Truncate Table [Error]

### ISSUE THREAD

**Issue by emresaracoglu** [izniburak/pdox#21]
Merhaba,
Veritabanina ait tabloyu kaldirma değil, sadece içini boşaltmak istediğimde bu hata ile karşılaşiyorum.
Klasik PDO sorgusun bu işlemsiz hatasiz olarak çalışmakta, gözden kacirdigim noktayi göremiyorum

```
$test = $db->query('TRUNCATE TABLE ?', ['testTablosu']);
	if ($test) {
		echo "<div class='notice notice-success'>All databases delete from MDM</div>";
	} else {
		echo "<div class='notice notice-danger'>All databases not delete from MDM</div>";
	}
```

Cikisi:
```
Database Error
Query: "TRUNCATE TABLE 'testTablosu'"
Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ''testTablosu'' at line 1
```

Bunun sebebi ne olabilir?

**Comment by izniburak** [comment]
Tablo adı tırnak işaretleri içerisinde yazıldığından hata veriyor olabilir.
Truncate işlemi için bunu deneyebilirsiniz:
```php
$db->table('testTablosu')->delete();
```
Herhangi bir koşul belirtmezseniz tüm kayıtlar silineceğinden, direkt olarak TRUNCATE komutu çalıştırılır.

**Comment by emresaracoglu** [comment]
Kesinlikle, bunu nasil düşünemedim :) 
Teşekkür ederim 👍
