### ISSUE TITLE
Toplama İşlemi (SUM)

### ISSUE THREAD

**Issue by emresaracoglu** [izniburak/pdox#24]
Merhaba,

Birkaç satırda yer alan sayılari toplamak için aşağidaki kod diziminde hata yapıyorum, acaba hata tam olarak nerede?

Düşünceme göre `total_row` kısmında hata yapıyorum ama emin değilim.

```
$arsivlenmisDokumanSayisi = $db->table('Dokumanlar')->sum('Arsivlenmis', 'total_row');
foreach ($arsivlenmisDokumanSayisi as $arsivlenmis) {
    echo $arsivlenmis->total_row; 
}
```

Teşekkürler

**Comment by izniburak** [comment]
```php
$db->table('Dokumanlar')->sum('Arsivlenmis', 'total_row')->getAll();
```

şeklinde dener misiniz?

**Comment by emresaracoglu** [comment]
Son kısım olan `->getAll();` nasıl da göremedim. Teşekkür ederim. 👍

**Comment by emresaracoglu** [comment]
Bu konu için son olarak `where `komutunu kullanmamiz mümkün mü?

`->where('formatTuru', $dokFormati)->getAll();`

Where komutunu kullandiğim zaman, sanki hiç yazmamış gibi davranmaya devam ediyor ve tüm tablodaki verileri topluyor. `Where` nasıl kullanabilirim?
