### ISSUE TITLE
Aynı tablodaki, aynı verileri yazdırma

### ISSUE THREAD

**Issue by emresaracoglu** [izniburak/pdox#26]
Merhaba,

Aynı tablodaki, aynı verileri nasıl yazdirabilirim? Amacım, aynı tablodaki kopya satırlari bulabilmek.

**Comment by izniburak** [comment]
Bu tamamen SQL bilgisi ile yapılacak bir şey. PDOx ile bir alakası yok. Direkt olarak query() metodu içerisine, sorgunuzu yazabilirsiniz.
