### ISSUE TITLE
Tablonun Ortalamasini Alabilmek (AVG)

### ISSUE THREAD

**Issue by emresaracoglu** [izniburak/pdox#27]
Merhaba,

Tablo `Sayilar`'ın için de yer alan `yuzdelikBirimler` kısmının ortalamasini alabilmek için; 

`$genelOrtalamasi = $db->table('Sayilar')->avg('yuzdelikBirimler')->getAll();`

sorgusundaki sonucu nasil yazdırmalıyım?
Teşekkürler

**Comment by izniburak** [comment]
```php
$db->table('test')->avg('id', 'avg_row')->get();
```
şeklinde dener misiniz?

**Comment by emresaracoglu** [comment]
```
$genelOrtalamasi = $db->table('Sayilar')->avg('yuzdelikBirimler', 'avg_row')->get();
echo $genelOrtalamasi ; 
```

Şeklinde çalıştırdım fakat hata ile karşılaştım.

`Fatal error: Uncaught ErrorException: Object of class stdClass could not be converted to string in /home/izniburak/public_html/Sonuclar.php:293 Stack trace: #0 `
