### ISSUE TITLE
LIKE İşlemleri

### ISSUE THREAD

**Issue by emresaracoglu** [izniburak/pdox#29]
Merhaba,

**LIKE** İşlem sonucunu ekrana nasıl yazdiliriyor?

`$db->like('title', '%burak%');`

Bunun için `foreach` kullanılmıyor sanırım(?)
Teşekkür ederim

**Comment by izniburak** [comment]
```php
$db->table('test')->like('title', '%burak%')->getAll();
```
şeklinde dener misiniz? Sorgunuzu yazdıktan sonra, get() veya getAll() metodunu kullanarak verileri çekmeniz gerekiyor.
