### ISSUE TITLE
Toplama İşlemlerinde Önbellek

### ISSUE THREAD

**Issue by emresaracoglu** [izniburak/pdox#31]
Merhaba,

Sorgu işlemlerinde önbelleği kullaniyorum ve oldukca yararli fakat tablo içerisindeki tüm verilerin sayısını ögrenmek için `cache(3600)` komutunu eklediğim takdirde tablo toplama işlemi örneğin `43.000` ise bi anda `0` (sıfır) düşmekte olup ve önbellek kaydını `0` şeklinde almaktadir.

`$db->numRows()`, önbellek formatını anlamadiği için mi bu durum söz konusu yoksa benim mi hatam var?

Teşekkürler

**Comment by izniburak** [comment]
En kısa zamanda inceleyeceğim. Cache'den gelen veriler için, numRows değeri güncellenmiyor sanırım. Teşekkürler.

**Comment by izniburak** [comment]
I fixed this. Please, update PDOx via composer or manually.

**Comment by emresaracoglu** [comment]
Teşekkürler.
