### ISSUE TITLE
Tablodaki Aynı Verileri Eleme

### ISSUE THREAD

**Issue by emresaracoglu** [izniburak/pdox#32]
Merhaba,

Aynı tablo içerisinde yer alan aynı veriler birden fazla ise ve yazırma işleminde, aynı veriden sadece bir kere yazılmasını sağlamak için nasil bir method uygulamak gerekiyor?

Örneğin;

id                | users
------------ | -------------
1 | Emre
2 | Burak
3 | Burak
4 | Katya
5 | Kayta

Çıkış:

> Emre
> Burak
> Katya

**Comment by izniburak** [comment]
Bkz: https://www.w3schools.com/sql/sql_distinct.asp

**Comment by emresaracoglu** [comment]
Elbette klasik MySQL sorgusu ile gercekleştirebiliyorum ancak PDOx ile bu işlemin nasil gerçekleştirildiğini sormak istemiştim.

**Comment by emresaracoglu** [comment]
Yada PDOx'da bunun için method var mı?

**Comment by izniburak** [comment]
```php
$db->table('test')->select('colum1, colum2, DISTINCT colum3')->......->getAll();
```
gibi deneyebilirsiniz.

**Comment by emresaracoglu** [comment]
Teşekkür ederim.
