### ISSUE TITLE
Birden Fazla Veri Ekleme

### ISSUE THREAD

**Issue by emresaracoglu** [izniburak/pdox#34]
Merhaba,

Birden fazla veriyi tek seferde tabloya eklemek PDOx ile mümkün mü?
Eğer mümkün ise örnek verebilirsiniz?

Mutlu haftasonu diliyorum.

**Comment by izniburak** [comment]
Insert metodu için şu an böyle bir özellik yok ama, üzerinde çalıştığım güncellemelerden biri bu. Yakın zamanda update gelecek.

**Comment by emresaracoglu** [comment]
Herhangi bir gelişme var mı acaba?
