### ISSUE TITLE
İki Farklı Tablodaki Farkı Bulabilmek

### ISSUE THREAD

**Issue by emresaracoglu** [izniburak/pdox#38]
Merhaba,

```
$db->select('DISTINCT id')
->table('test as t')
->join('foo as f', 't.id', 'f.t_id')
->where('t.status', 1)
->getAll();
```

Yukarıdaki sorgu işleminde iki farklı tabloyu birleştirmeyi sağlayabiliyorum ancak tam olarak amacim her iki tabloda olan verileri almak değil, `test` tablosunda olan verinin `foo` tablosunda karşılığı yok ise, `test` tablosundaki _ID_ numarasini yazdirmak istiyorum.

Özet olarak; `test` tablosunda _235135_ nolu değerin, `foo` tablosunda karşılığı yok ise, yazılmasını sağlamak.

Bunu PDOx ile nasıl sağlayabilirim?

**Comment by izniburak** [comment]
where metoduna gerekli şartları belirterek ve select kısmında da uygun alanları yazarak istediğiniz sonucu elde edebilirsiniz gibi duruyor. Pdox ile de örnek verdiğiniz şekilde kullanım yapabilirsiniz. Bu biraz SQL ile alakalı bir konu.
