### ISSUE TITLE
new where clause functions

### ISSUE THREAD

**Issue by jagroop** [izniburak/pdox#39]
hi @izniburak 

how about having clean __whereNull__ and __whereNotNull__

```php

  public function whereNull($where)
  {
    $where = $where . ' is null';
    if (is_null($this->where))
      $this->where = $where;
    else
      $this->where = $this->where . ' ' . 'and ' . $where;
    return $this;
  }
 
// will produce ``` where tbl.colmn is null```

  public function whereNotNull($where)
  {
    $where = $where . ' is not null';
    if (is_null($this->where))
      $this->where = $where;
    else
      $this->where = $this->where . ' ' . 'and ' . $where;
    return $this;
  }

// will produce ``` where tbl.colmn is not null```

```

Actually, I really missed these functions in my last project, so i had to extend your class.

Thanks !

**Comment by izniburak** [comment]
Hi, it seems good. after doing a few development on this code, we can add it to PDOx. Thanks!

**Comment by KrzysztofMadejski** [comment]
Why is it closed if it's not implemented? Current `where` doesn't offer any `IS NULL` support. I'd argue that such functionality should be implemented in current `where`.
