### ISSUE TITLE
Update ek ozellik

### ISSUE THREAD

**Issue by TheYkk** [izniburak/pdox#40]
https://github.com/ismail0234/pdodatabase/  bu kutuphaneyi incelerken cok guzel bir ozellik buldum sizde buna eklermisiniz
```
// UPDATE users SET point = point - 20 WHERE id = 9
$db->set('point','point - ?',20)->where('id',9)->update('users');
```

birde su debug
https://camo.githubusercontent.com/cdd091b38bc2e949d848282bba5980d3a417df17/687474703a2f2f692e696d6775722e636f6d2f766c644770754b2e706e67

**Comment by izniburak** [comment]
Güzel bir özellik olabilir. Geliştirme yapıyorum zaten, duruma göre böyle bir şey de ekleyebiliriz. Daha kullanışlı bir şekile getirmeye çalışalım.

Teşekkürler.

**Comment by TheYkk** [comment]
tabi ne zaman getitirsiniz?

**Comment by izniburak** [comment]
Henüz bilemiyorum, yoğunluğuma göre en kısa zamanda bazı geliştirmeler ekleme düşüncem var. Bunu da not aldım. 

Teşekkürler.

**Comment by emresaracoglu** [comment]
Acaba bu konuda herhangi bir gelişme var mı?

**Comment by izniburak** [comment]
Bazı yeni özellikler üzerinde çalışmalar yapıyorum ama iş yoğunluğundan dolayı ne yazık ki hızlı ilerleyemiyorum. Bu özellikte eklemeyi düşündüğüm şeylerden biri. En kısa zamanda yayınlama amacındayım.

**Comment by emresaracoglu** [comment]
@izniburak Tamamdir, teşekkürler 👍
