### ISSUE TITLE
query API does not allow you to set parameters as well as give all the results

### ISSUE THREAD

**Issue by vikassaklecha** [izniburak/pdox#43]
$db->query($sql, true); will give all the rows but does not allow you to send parameters.

$db->query($sql, $parameters); does not give you all the rows, but only one row.

**Comment by izniburak** [comment]
Ohh. I guess you can be right. I'll update library for this as soon. (in this week)

**Comment by izniburak** [comment]
Hi, @vikassaklecha 

I just updated the library and released new version for this. You could update library and try to use again.

By the way, Query method usage changed in this version. You could examine [query method](https://github.com/izniburak/PDOx/blob/master/DOCS.md#query) in documentation.  

Thanks!
