### ISSUE TITLE
need help

### ISSUE THREAD

**Issue by istoGer** [izniburak/pdox#47]
I tested out this class and have a problem.
I dont use composer.

the files are like this:

root/page.php
- include inc/func.inc.php
- some html, db-access via pdox

root/inc/func.inc.php
- include db.inc.php
- contains functions for db-access

root/inc/db.inc.php
- include Pdox.php
- include Cache.php
- define $config

root/inc/Pdox.php
root/inc/Cache.php

calling page.php executes the db-acess and shows content
calling a function from func.inc.php to get a value from db crashes the page.php

its for replacing the PdoDB-Class in this Projekt what didnt work with php >7.

please give me a help

**Comment by imsole** [comment]
oh，What is the wrong information?

**Comment by istoGer** [comment]
I assume, the error is in my code or understanding of the class.
but I cant catch it - thats why I asked for help

**Comment by imsole** [comment]
maybe, You can send a screenshot of your code.

**Comment by istoGer** [comment]
this is the relevant extraction of my code:
the db-action in page.php is working correct - but calling the function 
stops at : $fdb = new \Buki\Pdox($config);

//db.inc.php
<?php
require 'Pdox.php'; 
require 'Cache.php'; 

$config = [
    'host'      => 'xxx',
    'driver'    => 'mysql',
    'database'  => 'xxx',
    'username'  => 'xxx',
    'password'  => 'xxx,
    'charset'   => 'utf8',
    'collation' => 'utf8_general_ci',
    'prefix'    => ''
];

?>


// func.inc.php
<?php

require 'db.inc.php'; 


function getDbValue($num)
{
$back = 0;

$fdb = new \Buki\Pdox($config);

$row = $fdb->select('field')->table('table')->where('id', $num)->get();

if ($db->numRows() > 0) {
     $back = $row->field;
}

    return $back;
}

?>


//page.php
<?php

include 'func.inc.php';

// some html

$db = new \Buki\Pdox($config);

$servlist = $db->table('qs_service')->orderBy('sort_order')->getAll();

foreach ($servlist as $lserv) { 

    echo '<input name="service[]" id="service_'.$lserv->service_id.'" class="checkbox" value="'.$lserv->service_id.'" type="checkbox"';
    echo '>'.$lserv->description.'</td>';

}

    $neRow = !$neRow;

// some html

echo getDbValue(1);

// some html

?>

**Comment by istoGer** [comment]
sorry, last post went wrong

this is the relevant extraction of my code:
the db-action in page.php is working correct - but calling the function
stops at : $fdb = new \Buki\Pdox($config);

[code.txt](https://github.com/izniburak/pdox/files/2546048/code.txt)

**Comment by izniburak** [comment]
I guess, you could not access to $config variable in functions. For this, can you try to following:

```php
function sampleFunction($params) {
  global $config;
  // your codes...
}

```

**Comment by istoGer** [comment]
Yes, of course - many thanks !
a problem of replacing the other class

Another problem occured with a complex query. The previous used class find results, Pdox doesnt.
I used the $db->query 

the query is:
`SELECT qs_berater.id, qs_berater.firma, qs_berater.vorname, qs_berater.name, qs_berater.strasse, qs_berater.plz, qs_berater.ort, ACOS(SIN(RADIANS(lat)) * SIN(RADIANS(50.07286057)) + COS(RADIANS(lat)) * COS(RADIANS(50.07286057)) * COS(RADIANS(lon) - RADIANS(8.862515286))) * 6380 AS distance FROM ((qs_berater left join de_plz_koord on qs_berater.plz = de_plz_koord.plz)) where IFNULL(de_plz_koord.plz,'0')!='0' and qs_berater.plz != '' and user_status>0 and adress_sperre=0 and (den_is=1 or (den_mgl_kuend=1 and den_mgl_kuend_dat_u >1541380305)) group by qs_berater.id ORDER BY distance limit 0 , 7`

**Comment by izniburak** [comment]
Could you share screenshot of your code or related code blocks?

**Comment by istoGer** [comment]
$sql = the query above

$db = new \Buki\Pdox($config);

$rows = $db->query($sql)->fetchAll();

if ($db->numRows() == 0) {   // numRows always = 0

**Comment by izniburak** [comment]
I'll examine it. In fact, your sql code seems true, so i don't know why you get the error. 
Stay in touch.
Thanks.

**Comment by imsole** [comment]
I think you can replace this code with a value for a try.
`ACOS(SIN(RADIANS(lat)) * SIN(RADIANS(50.07286057)) + COS(RADIANS(lat)) * COS(RADIANS(50.07286057)) * COS(RADIANS(lon) - RADIANS(8.862515286))) * 6380`

**Comment by istoGer** [comment]
the problem is that numRows() =0 in the below code, but there are results in $rows 

`
$db = new \Buki\Pdox($confQS);

$rows = $db->query($sql)->fetchAll();

if ($db->numRows() == 0) {
`

**Comment by izniburak** [comment]
I guess I found the problem so I just fixed this issue and released a new version. Please update your library or dependencies through composer or manually.
