### ISSUE TITLE
where statement

### ISSUE THREAD

**Issue by istoGer** [izniburak/pdox#48]
is it possible to use the where-clause 
$where = [
	'name' => 'Burak',
	'age' => 23,
	'status' => 1
];

also for
'age' > 23,

?

**Comment by izniburak** [comment]
Hi @istoGer ,
Currently, It is not possible as you specified. But maybe you can do this like such as:

```php
$where = [
  'name' => 'Burak',
  'status' => 1
];

$query = $db->table('test')->where($where)->where('age', '>', 23)->getAll();
```

**Comment by istoGer** [comment]
@izniburak 
Thats ok - I didnt know, its possible to add somme where-conditions in the query like this.

Thats great work and perfect support !!
Thank you

**Comment by izniburak** [comment]
Thank you. I'm happy that it benefits to you :)
