### ISSUE TITLE
'Like' Olduğunda 'Where' Önemsiz

### ISSUE THREAD

**Issue by emresaracoglu** [izniburak/pdox#58]
Merhaba,

Aynı sorgu talebinde `LIKE` ve `WHERE` mevcut ise; sorgu sonucunda `WHERE` işlevini kaybediyor.

Örnek:

```
 $Gets = $db->table($ornekTablo)
->where('aktif', 1)
->like('terim', '%' . $aramaTerimi. '%')
->orLike('terim2', '%' .$aramaTerimi.%')
->limit(10)
->offset($offsetVerisi)
->getAll();
```

Aranmak istenen terim `aktif` olmasa dahi sonucta gösterimi sağlanıyor. `LIKE` İptal edildiği takdirde aktif olmayan terimlerin gösterilmiyor.

Teşekkürler

**Comment by izniburak** [comment]
Şurayı inceleyebilirsiniz: https://github.com/izniburak/pdox/blob/master/DOCS.md#grouped

**Comment by emresaracoglu** [comment]
Maalesef gün içerisinde birçok değişik şekilde denedim ancak bir türlü doğru sonuca ulaşamadim. `grouped` İle arama sonucunda veritabaninda mevcut tüm listeyi sunuyor. Pes ettim :)

Vaktiniz için teşekkürler

**Comment by izniburak** [comment]
Bilemiyorum, kaçırdığımız bir şey mi var? Oluşturduğunuz sql kodunu çıktı olarak alın ve gerçekten yazmak istediğiniz gibi olup olmadığını bir kontrol edin derim. PDOx içindeki query() metodu ile direkt olarak SQL yazarak çalıştırmayı deneyin bir de isterseniz.

Kolay gelsin.
