### ISSUE TITLE
Enhancement Request - FETCH_CLASS

### ISSUE THREAD

**Issue by trentramseyer** [izniburak/pdox#60]
Hello, 

I enjoy the code, I had to customize locally to add the ability to fetch by a custom class.

$sql->fetchAll(PDO::FETCH_CLASS, $this->class_name)

You might want to consider as a 3rd option to return data. 

Thank You !

**Comment by izniburak** [comment]
Hi @trentramseyer ,
Actually, this is good idea so thank you for your request. I will make somethings about that as soon as possible.
Thank you again!

**Comment by izniburak** [comment]
Hi @trentramseyer ,
I added FETCH_CLASS support in PDOx! To use it, You can update PDOx version via composer or manually.

For example:
```php
$db->...()->fetchAll('class', 'Classname');
// or
$db->...()->getAll('class', 'Classname');
```
Also, it works with get() and fetch() methods as well.

Thanks.
