### ISSUE TITLE
Version Info

### ISSUE THREAD

**Issue by istoGer** [izniburak/pdox#63]
Hi,
maybe you could insert a Versioninfo somewhere in files/packet.
It would make Version-Control in Projects easier.
thx

**Comment by izniburak** [comment]
Hi @istoGer 
Actually it would be good. I will add a method to get version info in PDOx.
Thanks for your feedback!

**Comment by izniburak** [comment]
Hi @istoGer 
I've added a constant variable to library for PDOx version. You can update PDOx version to use it.
Thanks!
