### ISSUE TITLE
about leftJoin

### ISSUE THREAD

**Issue by nFnK** [izniburak/pdox#64]
Merhaba,
"leftJoin('foo as f', 't.id', 'f._t_id')"  bu "ON t.id = f.t_id "
ben "ON t.id = f.t_id AND t.active= 1"  için leftJoin içerisinde nasıl yazılmalı?

**Comment by izniburak** [comment]
Merhabalar,
Buradaki `t.active = 1` kısmının tablo ilişkisi ile bir alakası yok gibi gözüküyor. Neden `where` kısmında yazmıyorsunuz? Yani şöyle;
```php
$db->table('test as t')->leftJoin('foo as f', 't.id', 'f.t_id')->where('t.active', 1)->getAll();
```
Join'ler için birden fazla ilişki parametresi belirtilmiyor şu an PDOx içerisinde ama bununla alakalı bir geliştirme yapmayı düşünüyorum. Eğer `SELECT xxx FROM yyy JOIN zzz ON a=b AND c=d`tarzı bir sorguya ihtiyacınız varsa, direkt olarak PDOx içersindeki `query`metodu ile bunu manuel yazabilirsiniz. Sizin queryiniz de `t.active = 1` kısmı dediğim gibi bir ilişkiyi temsil etmiyor aslında. Örnek olarak verdiğim şekilde deneyebilirsiniz.

Saygılar.

**Comment by nFnK** [comment]
Merhaba, Teşekkürler biliyorum onu. Farklı bir örnek de açıklayayım daha anlaşılır olur. Örnek : "LEFT JOIN secondTable f ON t.id = f.t_id AND t.status= f.status" bunu pdox leftJoin() içinde kullanamıyor muyum?

**Comment by izniburak** [comment]
Bunun için dediğim gibi ekstra bir geliştirme yapıyorum. Şu an mantıklı bir şekilde kullanımı yok malesef. Ama şu şekilde, biraz manasız ama işinize yarayan şekilde yazabilirsiniz:
```
...->leftJoin('secondTable s', 't.id', 'f.t_id AND t.status = f.status')...
```

İkinci ve üçüncü parametre = operatörü ile birleştiği için, üçüncü parametrenin sonuna ekleyeceğiniz şeyler de sorguya direkt olarak eklenmiş oluyor.

**Comment by nFnK** [comment]
Mantıklı bir çözüm :) teşekkürler. Ama yeni versiyonda buna çözüm üretirsin. Bu ORM i keyifli kullanıyorum teşekkürler.

**Comment by izniburak** [comment]
Şimdilik işinizi gördüyse, ne mutlu. Bu konuda bir update yapacağım dediğim gibi. Ek olarak; bu bir ORM değil. Query builder. Yanlışlık olmasın, onu da belirteyim.

Kolay gelsin :)
