### ISSUE TITLE
Sadece ilgili önbellek dosyasını yenileme

### ISSUE THREAD

**Issue by emresaracoglu** [izniburak/pdox#68]
Merhaba,

Sadece ilgili bir sorguya ait önbellek dosyasını yenilemek mümkün mü?

Teşekkürler

**Comment by izniburak** [comment]
Merhaba @emresaracoglu 
Sorununu tam olarak anlayamadım. Biraz daha açıklayabilir misin?

Teşekkürler.

**Comment by emresaracoglu** [comment]
Önbellek klasöründe binlerce sorgu bulunuyor ancak bazı sorgular farklı sayfalarda yeniden sorgulanması gerekiyor.Buraya kadar sorun ancak önbellek ile sorgu sonucu alınan sayfalarda ise hala eski sonuc verileri listelenmektedir. Bunun icin sorgu dosyası ne ile sifreleniyor ise klasör içinde sorgu dosyasının ismi aranır ve silinir, sonra da yeni sorgu talep edilir. Bunu yapmak yerine direkt şekilde sorgu dosyası nasıl yenilebilir?  -------- Original Message --------Subject: Re: [izniburak/pdox] Sadece ilgili önbellek dosyasını yenileme (#68)From: İzni Burak Demirtaş To: izniburak/pdox CC: Emre Saracoglu ,Mention Merhaba @emresaracoglu

Sorununu tam olarak anlayamadım. Biraz daha açıklayabilir misin?

Teşekkürler.



—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/izniburak/pdox/issues/68?email_source=notifications\u0026email_token=AACIX4A4AQRBQ3YQIV7DPE3QWRATTA5CNFSM4JTIYOWKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEFRY4NY#issuecomment-560172599",

"url": "https://github.com/izniburak/pdox/issues/68?email_source=notifications\u0026email_token=AACIX4A4AQRBQ3YQIV7DPE3QWRATTA5CNFSM4JTIYOWKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEFRY4NY#issuecomment-560172599",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by izniburak** [comment]
Sorgunun yeniden çalışmasını ve cache'den gelmemesini istiyorsanız; neden cache'liyorsunuz? O sorguyu direkt olarak cache'den çıkarabilirsiniz. Zaten böyle bir ihtiyacınız varsa, o sorgu için cache kullanmanız uygun bir durum gözükmüyor.

**Comment by emresaracoglu** [comment]
Yük bakımından ağır bir sorgu olduğu için önbellek ihtiyaci doğuyor, yeniden sorgu gereksimi ise çok ender şekilde gerekebiliyor. Ancak çözümü buldum sayılır, vaktiniz için teşekkür ederim.
