### ISSUE TITLE
Call to method pdo::prepare

### ISSUE THREAD

**Issue by coutofx** [izniburak/pdox#7]
perform queries using query prepare ?

**Comment by izniburak** [comment]
If you want to use the methods of the PDO library, use $db->pdo.

Example:

> $db = new \Buki\Pdox($config);
> 
> $query = $db->pdo->prepare( ... );
> $query->execute( ... );
> 
> $db->pdo->query( ... )->fetch( ... );


But, you can create advanced queries using the QUERY method of PDOx library.

Example:

> $db = new \Buki\Pdox($config);
> 
> $db->query("SELECT * FROM test WHERE id = ? AND status = ? LIMIT 10", [10, 1]);

Received data is filtered for security. Quote method to use the PDO library here.
info: http://php.net/manual/en/pdo.quote.php
