### ISSUE TITLE
how can i use this inside model class path?  

### ISSUE THREAD

**Issue by tonmooy** [izniburak/pdox#76]
how can i use this pdo object inside user model class path? for make database access easier and more efficient

$records = $db->table('users')
		->getAll();
class User
{
    

    public $id;
    public $name;
   

    public function getName()
    {
         return $this->name;
    }
}

some thing like that $result = $pdo->fetchAll(PDO::FETCH_CLASS, "User");

**Comment by izniburak** [comment]
Hi @tonmooy ,
You can use like that:
```
$db->...()->fetchAll('class', 'YOUR_CLASS_NAME');
// or
$db->...()->getAll('class', 'YOUR_CLASS_NAME');
```
First parameter is fetch type for PDOx.
Thanks.

**Comment by tonmooy** [comment]
> Hi @tonmooy ,
> You can use like that:
> 
> ```
> $db->...()->fetchAll('class', 'YOUR_CLASS_NAME');
> // or
> $db->...()->getAll('class', 'YOUR_CLASS_NAME');
> ```
> 
> First parameter is fetch type for PDOx.
> Thanks.

thank you it's working now
