### ISSUE TITLE
Select Count - Where - Or Where ile Nasıl saydırma yapabilirim?

### ISSUE THREAD

**Issue by burakalac4** [izniburak/pdox#77]
Mükerrer kaydı önemlemek için saydırma işlemi yapıyorum burada takılı kaldım
```$say = $db->table('authme')->count('authme_username', 'uye')->where('authme_username', $username)->get();```
Bu şekilde sorgu yapmaya çalıştım 
```$say->uye```
 sayısını alabiliyorum fakat sorgumu bu şekilde nasıl yapabilirim?
```WHERE authme_username = username OR authme_mail  = abc@xyz.com```
kontrol için kullanacağım bu şekilde yapma şansım var mı yoksa ikisi içinde ayrı ayrı mı sorgulatmam lazım?
Teşekkürler, @izniburak

**Comment by izniburak** [comment]
Merhabalar,
Birden fazla `where` tanımlaması yapabilirsiniz. Örnek;

```php
$db->table('test')->where('column_1', 'value_1')->orWhere('column2', 'value_2')->get();
```
PDOx dokümanını detaylı olarak okursanız, orada örnekler ve kullanımlar mevcut.

**Comment by burakalac4** [comment]
> Merhabalar,
> Birden fazla `where` tanımlaması yapabilirsiniz. Örnek;
> 
> ```
> $db->table('test')->where('column_1', 'value_1')->orWhere('column2', 'value_2')->get();
> ```
> 
> PDOx dokümanını detaylı olarak okursanız, orada örnekler ve kullanımlar mevcut.

Dökümanı okudum evet o kısmı gördüm fakat sormak istediğim şuydu

```
$data= [
	'username' => $username,
	'password' => $password,
	'status' => 1
];
$db->table('test')->where($data)->getAll();
```
Bu şekilde yapıp saydırmak istiyorum 
Normalde saydırma işlemini pdox ile şu şekilde yapıyorum (Doğru yada yanlış bilmiyorum)
```
$say = $db->table('test')->count('username', 'uye')->where('username', $username)->get();
print_r($say->uye);
```
Burda orwhere yapabiliyoruz fakat or değilde OR değilde and şekilde yapmak istiyorum orWhere yerine ->where bu şekilde bir where daha mı eklememiz gerekiyor? Array kabul etmedi denediğimde.
Sorum budur hocam, ilginiz için teşekkürler.

**Comment by izniburak** [comment]
Probleminizi tam olarak anlayamadım. `where` kullanımından sonra tekrar `->where` yapıp, sıralayabilirsiniz dediğiniz gibi. Tam olarak sorunu anlayabilsem, daha net yardımcı olabilirdim ama, durum PDOx ile alakalı değil, spesifik bir şey gözüküyor.
