### ISSUE TITLE
Cache Çalışma Mantığı

### ISSUE THREAD

**Issue by munkererkadam** [izniburak/pdox#79]
Merhabalar,

$getir = $db->select('email')->table('users')->limit(5)->cache(60)->getAll();

Örnek olarak, yukarıda bulunan cache(60) parametresi, 60 saniyelik cache klasöründe cache tutmakta. Fakat sizince bildiğiniz gibi bazı durumlarda bu süreyi belirlerken dikkatli olmalıyız. Örneğin;

"Bir üye listesi yaparken cache 60 saniye  mi çalıştırmak mantıklı yoksa 180 saniye mi şu durumda bilemiyorum."

Sizlerden ricam, Cache çalışma mantığını anlatabilir misiniz? 

Teşekkürler.

**Comment by izniburak** [comment]
@munkererkadam Merhabalar,
PDOx içerisinde basitçe kullanılabilecek şekilde file based bir cache imkanı sağlıyor. Bunun kullanımı ile alakalı kararlar tamamen sizin uygulamanızda ihtiyaçlarınıza bağlı. Sürekli güncellenen bir daha dinamik bir kısımda cache kullanmak veya cache süresini uzun tutmak mantıksız olacaktır. Harici durumlarda süre arttırılabilir, farklı alternatifler denenebilir. Bunun kararı tamamen sizde. Yani cachenin ne yaptığı, ne amaçladığı belli aslında; kendi business logic'inize bunu oturtuyor olmanız lazım. 

Bunun dışında farklı cache mekanizmaları da kullanabilirsiniz. (Redis, Memcache vs..)

Kolay gelsin.
