### ISSUE TITLE
Sorgularinda IF/ELSE formatlari

### ISSUE THREAD

**Issue by emresaracoglu** [izniburak/pdox#8]
Merhaba, 

Sorgularda IF/ELSE formatlarindan örnekler sunmanız mümkün mü?

**Comment by izniburak** [comment]
Tam olarak nasıl bir örnek istiyorsunuz? Yardımcı olmaya çalışayım.

**Comment by emresaracoglu** [comment]
```
$TestConnection= new mysqli("localhost", "", "", "");
if ($TestConnection->connect_error) {
	echo " <span class='label label-danger'>Failed</span> ";
} else {  echo " <span class='label label-success'>Working</span> ";}
```

Bu tarz bir IF/ELSE durumlarini belirtebilir misiniz? Örnekleri siz de dilerseniz döküman içeriğinde ekleyebilirsiniz, böylelikle daha zengin içerik sağlanabilir.

**Comment by izniburak** [comment]
Bağlantı için ekstra bir kontrol yapmanıza gerek yok. TRY-CATCH ile zaten hatalar yakalanıyor ve işlem sonlandırılıyor. Bunun dışında sorgu işlemlerinde bazı kontrollere ihtiyaç olursa, bunlar direkt olarak atama yaptığınız değişken üzerinden yapılabiliyor. Değişkenin değer kontrolünü sağlayarak işlem yapabiliyorsunuz. Veya toplam kayıt sayısını karşılaştırma yapabilirsiniz. 

```php
$query = $db->table('test')->where('status', 1)->getAll();
if($db->count() > 0)
{
  // code ... 
} else 
{
  // code .. 
}
```
gibi. Benzer örnekleri sınıf üzerindeki bazı geliştirmeler bittikten sonra, dökümantasyona da ekleyeceğim. Örnekleri çoğaltacağım. Şu an bir kaç yeni metot ve özellik üzerinde geliştirmeler yapıyorum. 

Önerileriniz için teşekkürler. Aklınıza gelen şeyler olursa, dinlemek isterim.
