### ISSUE TITLE
Insert issue

### ISSUE THREAD

**Issue by tonmooy** [izniburak/pdox#80]
When i try to insert js code inside my blog it's Show 403 error why how can i post js code inside insert function? <script>etc </script>  

Forbidden
You don't have permission to access this resource.

Additionally, a 403 Forbidden error was encountered while trying to use an ErrorDocument to handle the request.

**Comment by izniburak** [comment]
Hi @tonmooy ,
Are you sure that issue is about PDOx library ?

**Comment by tonmooy** [comment]
> Hi @tonmooy ,
> Are you sure that issue is about PDOx library ?

yes please give me a solution 😟 try to insert some js tag inside using $_POST method

**Comment by tonmooy** [comment]
> Hi @tonmooy ,
> Are you sure that issue is about PDOx library ?

is it host problem or anything else?

**Comment by tonmooy** [comment]
it's work on local host but in namecheap  host it's show this error

**Comment by izniburak** [comment]
I think this problem might be related with web server security. Pdox has no restriction like that. Maybe you can check your web server configuration or security level.
