### ISSUE TITLE
Deprecated: Unparenthesized `a ? b : c ? d : e` is deprecated. Use either `(a ? b : c) ? d : e` or `a ? b : (c ? d : e)`

### ISSUE THREAD

**Issue by VelikyName** [izniburak/pdox#92]
`$config['port'] = isset($config['port'])
            ? $config['port']
            : strstr($config['host'], ':') ? explode(':', $config['host'])[1] : '';`
            --------->
            `$config['port'] = isset($config['port'])
            ? $config['port']
            : (strstr($config['host'], ':') ? explode(':', $config['host'])[1] : '');`

**Comment by izniburak** [comment]
Hi, 
Thank you for your feedback. It has been fixed!
