### ISSUE TITLE
Hata Yakalama Durumu

### ISSUE THREAD

**Issue by azizsenturk** [izniburak/pdox#93]
Merhabalar, atılan sorgu sonrası "Duplicate entry", "Data too long" gibi hataları network üzerinde görüyorum ancak sistemi öldürüp yazdığı için api sonuncuna bağlayamıyorum. Çalıştırılan sorgunun sonucunu success veya failed olarak yakalayabileceğim ve hatayı apiye bağlayabileceğim bir sorgu veya önerebileceğiniz bir yöntem var mıdır acaba?

**Comment by izniburak** [comment]
Exception'ları yakalayarak işlem yapılabilir aslında ama, PDOx özelinde exceptional durumları daha iyi handle edebilecek bir düzenleme üzerinde çalışıyorum. Sonraki release ile yayınlama düşüncem var. Bu konuda başka fikirleriniz varsa, onları da dinlemekten memnun olurum.

**Comment by azizsenturk** [comment]
Slim Framework üzerinden bir api yazıyorum değişkene pdox'i bağladım add, update ve delete fonksiyonunda cevap olarak  1 veya boş(yada hata nedenini die metodu ile) alıyordum, değişkende exception'ları yakalamaya çalışmıştım ancak bir türlü yakalayamadım benim eksiğim olabilir. 
Nacizane şöyle bir fikir sunabilirim eğer hoşunuza giderse:
Add sonrasında lastId ile get çalıştırıyorum, update sonrasında ise update id'si ile get çalıştırarak o satır bilgilerini çekiyorum. bunun yerine add ve update fonksiyonları sonrasında işlem doğru ise değişkene cevap olarak işlem yapılan satır dönse veya hatalı ise hata kodu ile mesajı dönse api kullanımı açısından rahatlatıcı bir çözüm olabilir gibi geldi

**Comment by izniburak** [comment]
Şu an ki durumda `debug` ayarı açıksa, query ve error'u çıktı olarakv eriyor ama kapalı durumda (production için) exception atıyor. Bu exceptionı catch ederek kullanmanız mümkün.

**Comment by azizsenturk** [comment]
Debug modunu kapatmıştım ancak yakalayamamıştım catch ile tekrardan deneyeyim teşekkür ederim
