### ISSUE TITLE
Birden fazla grouped ve OR

### ISSUE THREAD

**Issue by ozgurg** [izniburak/pdox#95]
Merhaba, birden fazla **grouped** kullandığımda bunları **OR** ile nasıl ayırabilirim?

Dökümandaki **grouped** örneğini çalıştırdığımda aşağıdaki sonucu alıyorum ve bu gayet normal.

```php
$db->table('users')
	->grouped(function($q) {
		$q->where('country', 'TURKEY')->orWhere('country', 'ENGLAND');
	})
	->where('status', 1)
	->getAll();
# Ouput: "SELECT * FROM users WHERE (country='TURKEY' OR country='ENGLAND') AND status ='1'"
```

Ama birden fazla **grouped** kullandığımda bu ikisini **AND** ile birleştiriyor.
```php
$db->table('users')
    ->grouped(function($q) {
        $q->where('country', 'TURKEY')->orWhere('country', 'ENGLAND');
    })
    ->grouped(function($q) {
        $q->where('country', 'GERMANY')->orWhere('country', 'FRANCE');
    })
    ->where('status', 1)
    ->getAll();
# Ouput: "SELECT * FROM users WHERE (country = 'TURKEY' OR country = 'ENGLAND') AND (country = 'GERMANY' OR country = 'FRANCE') AND status = 1"
```

Hedeflediğim sonuç:
```sql
SELECT * FROM users WHERE (country = 'TURKEY' OR country = 'ENGLAND') OR (country = 'GERMANY' OR country = 'FRANCE') AND status = 1
```

**Comment by izniburak** [comment]
Selamlar @ozgurg ,
Aslında ikinci `grouped` içerisindeki builder'a `->orWhere` diye başlaman yeterli olacaktır. Aslında yazdığın sorguyu gruplarken, sorguyu yazmaya devam ediyorsun ve ilk şart olarak `orWhere` belirtirsen, gruplama işlemi `OR` olarak devam eder. Sonrasında bağlayacağın diğer şartlar, grubun içerisini kapsayacak ama.

**Comment by ozgurg** [comment]
> Selamlar @ozgurg ,
> Aslında ikinci `grouped` içerisindeki builder'a `->orWhere` diye başlaman yeterli olacaktır. Aslında yazdığın sorguyu gruplarken, sorguyu yazmaya devam ediyorsun ve ilk şart olarak `orWhere` belirtirsen, gruplama işlemi `OR` olarak devam eder. Sonrasında bağlayacağın diğer şartlar, grubun içerisini kapsayacak ama.

Hmm, teşekkür ederim. 😊

Sonradan bakan olursa diye şu şekilde yaptım:
```php
$db->table('users')
    ->grouped(function($q) {
        $q->where('country', 'TURKEY')->orWhere('country', 'ENGLAND');
    })
    ->grouped(function($q) {
        $q->orWhere('country', 'GERMANY')->orWhere('country', 'FRANCE'); // Baştaki where, orWhere oldu.
    })
    ->where('status', 1)
    ->getAll();
# Ouput: "SELECT * FROM users WHERE (country = 'TURKEY' OR country = 'ENGLAND') OR (country = 'GERMANY' OR country = 'FRANCE') AND status = 1"
```
