### ISSUE TITLE
'where' için 'FIND_IN_SET' methodu

### ISSUE THREAD

**Issue by emresaracoglu** [izniburak/pdox#97]
Merhaba,

Kolon içerisinde yer alan birçok verinin ayrıştırılmasını sağlamak amaçlı `FIND_IN_SET` methodunu bir sonraki güncelleme de ekleme olanağınız olursa sevinirim.

Kısa bir örnek için [bu linki](https://stackoverflow.com/a/23633103/14679852) ziyaret edebilirsiniz.

Sağlıklı ve iyi günler dilerim.

**Comment by izniburak** [comment]
Merhaba @emresaracoglu ,
Kısa zaman içerisinde bazı ufak güncellemeler içerecek bir versiyon yayınlamayı düşünüyordum. Bu özelliği de kazandırabiliriz diye düşünüyorum. Teşekkürler tavsiyen için.
